@startuml Demo Networking Diagram

object "Internet" as internet
internet : <img:"../networking_icons/cloud_internet_128px.png">
internet : Public IP Addr: **WAN DHCP**
internet : ISP: **<Name>**

object "Modem" as modem
modem : <img:"../networking_icons/modem-router_square-bw_128px.png">
modem : IP Addr: **192.168.200.1**

object "Router" as router
router : <img:"../networking_icons/router_circle-with-four-arrow-incoming-inside_128px.png">
router : IP Addr: **192.168.0.1**

object "Semi-Smart Switch" as switch1
switch1 : <img:"../networking_icons/switch_symbol-bw-ios-7_128px.png">
switch1 : IP Addr: **192.168.0.2**
switch1 : Make: **** Model: ****
switch1 : **8-ports**

object "Dumb Switch" as switch2
switch2 : <img:"../networking_icons/switch_symbol-bw-ios-7_128px.png">
switch2 : IP Addr: **Unmanaged**
switch2 : **5-ports**

object "Wi-Fi AP" as wifiap1
wifiap1 : <img:"../networking_icons/antenna_tower-3-legs-omni-signal_128px.png">
wifiap1 : IP Addr: **192.168.0.3**
wifiap1 : Make: **Ubiquiti** 
wifiap1 : Model: **UniFi AP - UAP Pro**

object "Laptop" as laptop1
laptop1 : <img:"../networking_icons/laptop_black-keyboard-white-touchpad_064px.png">
laptop1 : Hostname: **<Name>**

internet <- "F-Type" modem : RG-6
modem <- router : Cat6
router "eth1" <-- switch1
switch1 <-> switch2
switch2 <-> wifiap1
wifiap1 <..> laptop1 : <img:"../networking_icons/wifi-signal-symbol_square-bars_016px.png">5GHz

@enduml