@startuml Devicons_and_Font_Awesome-example2
/'
tupadr3/plantuml-icon-font-sprites

https://github.com/tupadr3/plantuml-icon-font-sprites

http://plantuml.com/guide

21 Standard Library -> 21.4 Devicons and Font Awesome library
'/

!include <tupadr3/common>
!include <tupadr3/devicons/mysql>

/'
<PREFIX>_<NAME>(alias)
<PREFIX>_<NAME>(alias,label)
<PREFIX>_<NAME>(alias,label,shape)
<PREFIX>_<NAME>(alias,label,shape,color)
'/

DEV_MYSQL(db1)
DEV_MYSQL(db2,label of db2)
DEV_MYSQL(db3,label of db3,database)
DEV_MYSQL(db4,label of db4,database,red) #DeepSkyBlue

@enduml
