@startuml Demo_Networking_Diagram

' skinparam componentStyle uml2

/'
http://plantuml.com/guide
21 Standard Library
'/

!include <tupadr3/common>
'https://github.com/tupadr3/plantuml-icon-font-sprites
!include <tupadr3/font-awesome/server>
!include <tupadr3/font-awesome/database>
!include <tupadr3/material/phone_android>
!include <tupadr3/devicons/raspberry_pi>
'https://github.com/Roemer/plantuml-office
!include <office/Servers/application_server_blue>
!include <office/Servers/file_server>
' OFF_FILE_SERVER(fileserver1,File Server)
!include <office/Devices/switch>
'OFF_SWITCH(dumbswitch2,Dumb Switch)


rectangle internet [
<img:"networking_icons/cloud_internet_128px.png">
Public IP Addr: **WAN DHCP**
ISP: **<Name>**
]

rectangle modem [
<img:"networking_icons/modem-router_square-bw_128px.png">
IP Addr: **192.168.200.1**
]

rectangle router [
<img:"networking_icons/router_circle-with-four-arrow-incoming-inside_128px.png">
IP Addr: **192.168.0.1**
]

rectangle switch1 [
<img:"networking_icons/switch_symbol-bw-ios-7_128px.png">
IP Addr: **192.168.0.2**
Make: **** Model: ****
**8-ports**
]

rectangle switch2 [
<img:"networking_icons/switch_symbol-bw-ios-7_128px.png">
IP Addr: **Unmanaged**
**5-ports**
]

rectangle wifiap1 [
<img:"networking_icons/antenna_tower-3-legs-omni-signal_128px.png">
IP Addr: **192.168.0.3**
Make: **Ubiquiti** 
Model: **UniFi AP - UAP Pro**
]

rectangle laptop1 [
<img:"networking_icons/laptop_black-keyboard-white-touchpad_064px.png">
Hostname: **<Name>**
]

rectangle mediaserver [
OFF_FILE_SERVER(fileserver1,File Server)
OFF_APPLICATION_SERVER_BLUE(appserverblue,Media Server)
]

/'
<PREFIX>_<NAME>(alias)
<PREFIX>_<NAME>(alias,label)
<PREFIX>_<NAME>(alias,label,shape)
<PREFIX>_<NAME>(alias,label,shape,color)
'/

MATERIAL_PHONE_ANDROID(androidphone1,Android)

'FA_SERVER(web1,web1) #Green

DEV_RASPBERRY_PI(raspberrypi1,Pi Hole)

() "Jumper 1" AS jump1A
() "Jumper 1" AS jump1B

internet "WAN" <- "F-Type" modem : "    RG-6    "
' modem "F-Type" <-- internet : RG-6
modem <- router : Cat6
'router --> modem : Cat6
router "eth1" <-- switch1
'switch1 <-> switch2
'switch2 <-> switch1
switch1 <- jump1A
jump1A - jump1B : "In-Wall Cat6"
jump1B -> switch2
switch1 <--> raspberrypi1
mediaserver <-> switch1
switch2 <-> wifiap1
'switch2 -> speaker1
'wifiap1 <-> switch2
wifiap1 <..> laptop1 : <img:"networking_icons/wifi-signal-symbol_square-bars_016px.png">2.4GHz
wifiap1 <..> androidphone1  : <img:"networking_icons/wifi-signal-symbol_square-bars_016px.png">2.4/5GHz

@enduml