
' 15.11 Include Salt
' see: http://forum.plantuml.net/2427/salt-with-minimum-flowchat-capabilities?show=2427#q2427

@startuml Include Salt Example
(*) --> "
{{
	salt
	{+
	<b>an example
	choose one option
	()one
	()two
	[ok]
	}
}}
" as choose
choose -right-> "
{{
	salt
	{+
	<b>please wait
	operation in progress
	<&clock>
	[cancel]
	}
}}
" as wait
wait -right-> "
{{
	salt
	{+
	<b>success
	congratulations!
	[ok]
	}
}}
" as success
wait -down-> "
{{
	salt
	{+
	<b>error
	failed, sorry
	[ok]
	}
}}
"
@enduml
