@startuml OpenIconic Example
/'
http://plantuml.com/guide
16. Creole -> 16.10. OpenIconic
'/
' You can use the following syntax: <&ICON_NAME>
title: <size:20><&heart>Use of OpenIconic<&heart></size>
class Wifi
note left
	Click on <&wifi>
end note
@enduml